[project]
name = "vscode-python"
version = "0.1.0"
description = "LLM lab for ASR and translation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.isort]
profile = "black"
line_length = 88

[tool.black]
line-length = 88
