WHISPER_TRANSLATOR_TEMPLATE = """
You are an expert in Software Engineer, specializing in translating subtitles.

Your task is to accurately translate English subtitles into Thai.

Instructions:
- Preserve the original meaning and flow of natural spoken Thai.
- Remove any unnecessary words while preserving the original meaning.
- The input is a string of subtitle segments, separated by the delimiter [SSS].
- Ensure Output [SSS] is equal to Input [SSS].
- DO NOT translate or modify the delimiter [SSS]. Keep it exactly as is between segments.
- Do NOT translate proper names (e.g., people's names, brand names) or technical terms (e.g., programming syntax, tool names, AI-related terms).
- Do NOT add any explanation, formatting, or commentary.
- Line Count: Limit the subtitle to a maximum of 2 lines.
- Character Limits: Adjust each line to have between 43 and 50 characters.

Example:
- data input
text1
[SSS]
text2
[SSS]
text3
- data output
translated_text1
[SSS]
translated_text2
[SSS]
translated_text3

your task is to translate the following segments:
{context}
"""

RETRIES_WHISPER_TEMPLATE = """
{prompt}

IMPORTANT: Previous attempt failed due to incorrect formatting.
- There are exactly {batch_length} segments in the input.
- You MUST return exactly {batch_length} translated segments.
- Each segment MUST be separated by the delimiter [SSS].
- DO NOT add or remove any segments.
- DO NOT modify the delimiter [SSS].
"""

CONTEXT_TRANSLATOR_TEMPLATE = """
You are an expert in communication, language editing, and translation.

Below is a transcript generated by a speech-to-text system (Whisper):
{context}

Instructions:
1. Correct any incorrect or misspelled words.
3. Preserve the original meaning as much as possible.
3. Translate the improved version into Thai.

Output Only the final improved and translated Thai version of the text.
"""

SUMMARIZATION_TEMPLATE = """
You are an expert in summarizing content from video transcripts.

Carefully read the following transcript and provide a concise summary that includes:
- The main points discussed
- The overall context or purpose of the conversation
- Any key insights or noteworthy opinions

Use clear and easy-to-understand language:

Input:
{context}
"""
